/* ============================================================
   WebsiteKu — Template Data (50 templates across 5 categories)
   ============================================================ */

const WA_NUMBER = '6281234567890'; // Ganti dengan nomor WhatsApp Anda

const CATEGORIES = [
  { id: 1, name: 'Restoran & Kuliner',       icon: '🍽️', slug: 'restoran' },
  { id: 2, name: 'Property & Konstruksi',    icon: '🏠', slug: 'property' },
  { id: 3, name: 'Kesehatan & Kecantikan',   icon: '💊', slug: 'kesehatan' },
  { id: 4, name: 'Digital & Teknologi',      icon: '💻', slug: 'digital' },
  { id: 5, name: 'UMKM & Bisnis Umum',       icon: '🛍️', slug: 'umkm' },
];

const TEMPLATES = [
  /* ===========================
     KATEGORI 1 — RESTORAN & KULINER
     =========================== */
  {
    id: 'r01', cat: 1, catName: 'Restoran & Kuliner',
    name: 'WebsiteKu Cafe Modern',
    style: 'startup',
    primary: '#FF6B35', secondary: '#FFD166', accent: '#06D6A0',
    description: 'Cafe kekinian dengan tampilan bold dan penuh warna. Cocok untuk coffee shop dan kafe modern.',
    tags: ['cafe', 'kopi', 'kekinian', 'millennial'],
    headline: 'Kafe Terbaik di Kota',
    sub: 'Nikmati kopi premium dan suasana nyaman yang tak terlupakan.',
    menu: ['Espresso', 'Cappuccino', 'Matcha Latte', 'Pastry'],
  },
  {
    id: 'r02', cat: 1, catName: 'Restoran & Kuliner',
    name: 'WebsiteKu Coffee House',
    style: 'minimalist',
    primary: '#3D2314', secondary: '#C9A227', accent: '#F5E6D3',
    description: 'Tampilan minimalis elegan untuk coffee house premium. Bersih, hangat, dan mengundang.',
    tags: ['kopi', 'minimalis', 'premium', 'cozy'],
    headline: 'Where Every Sip Matters',
    sub: 'Specialty coffee dari biji pilihan terbaik, diseduh dengan penuh dedikasi.',
    menu: ['Single Origin', 'Cold Brew', 'Pour Over', 'Affogato'],
  },
  {
    id: 'r03', cat: 1, catName: 'Restoran & Kuliner',
    name: 'WebsiteKu Sushi Premium',
    style: 'luxury',
    primary: '#C9000B', secondary: '#F5C518', accent: '#FFFFFF',
    description: 'Restoran sushi mewah dengan desain bernuansa Jepang modern. Elegan dan berkelas.',
    tags: ['sushi', 'jepang', 'premium', 'mewah'],
    headline: 'Seni Kuliner Jepang Otentik',
    sub: 'Menghadirkan cita rasa sushi premium langsung dari tangan chef berpengalaman.',
    menu: ['Omakase', 'Salmon Sashimi', 'Dragon Roll', 'Wagyu Nigiri'],
  },
  {
    id: 'r04', cat: 1, catName: 'Restoran & Kuliner',
    name: 'WebsiteKu Steak House',
    style: 'dark',
    primary: '#C0392B', secondary: '#F39C12', accent: '#ECF0F1',
    description: 'Steak house berkarakter dengan tema gelap maskulin. Kuat, bold, dan menggugah selera.',
    tags: ['steak', 'daging', 'dark', 'premium'],
    headline: 'The Perfect Steak Experience',
    sub: 'Daging pilihan grade premium, dimasak sempurna untuk kepuasan Anda.',
    menu: ['Wagyu A5', 'Ribeye', 'T-Bone', 'Tenderloin'],
  },
  {
    id: 'r05', cat: 1, catName: 'Restoran & Kuliner',
    name: 'WebsiteKu Bakery',
    style: 'elegant',
    primary: '#D4956A', secondary: '#F8E8D4', accent: '#8B4513',
    description: 'Toko roti artisan dengan sentuhan elegan hangat. Sempurna untuk bakery dan pastry shop.',
    tags: ['bakery', 'roti', 'pastry', 'artisan'],
    headline: 'Freshly Baked with Love',
    sub: 'Setiap roti dibuat dengan bahan terbaik dan cinta yang tulus setiap harinya.',
    menu: ['Croissant', 'Sourdough', 'Cinnamon Roll', 'Pain au Chocolat'],
  },
  {
    id: 'r06', cat: 1, catName: 'Restoran & Kuliner',
    name: 'WebsiteKu Street Food',
    style: 'neon',
    primary: '#FF0090', secondary: '#00FF41', accent: '#FFD700',
    description: 'Street food energik dengan vibes malam kota. Neon dan penuh semangat.',
    tags: ['street food', 'neon', 'malam', 'energik'],
    headline: 'RASA JALANAN KOTA',
    sub: 'Kuliner autentik jalanan yang menggoyang lidah sejak 1995.',
    menu: ['Mie Ayam', 'Bakso', 'Sate Taichan', 'Takoyaki'],
  },
  {
    id: 'r07', cat: 1, catName: 'Restoran & Kuliner',
    name: 'WebsiteKu Seafood',
    style: 'corporate',
    primary: '#006994', secondary: '#00B4D8', accent: '#CAF0F8',
    description: 'Restoran seafood profesional dengan tampilan bersih dan terpercaya.',
    tags: ['seafood', 'ikan', 'laut', 'segar'],
    headline: 'Segar dari Laut ke Meja Anda',
    sub: 'Seafood pilihan terbaik dengan proses penyimpanan berstandar internasional.',
    menu: ['Kepiting Saus Tiram', 'Udang Bakar', 'Cumi Goreng', 'Lobster'],
  },
  {
    id: 'r08', cat: 1, catName: 'Restoran & Kuliner',
    name: 'WebsiteKu Fine Dining',
    style: 'premium',
    primary: '#C9A227', secondary: '#0F1629', accent: '#FFFFFF',
    description: 'Fine dining mewah dengan presentasi eksklusif. Untuk pengalaman makan berkelas tinggi.',
    tags: ['fine dining', 'mewah', 'eksklusif', 'premium'],
    headline: 'An Unforgettable Dining Experience',
    sub: 'Kami menyajikan lebih dari sekadar makanan — sebuah perjalanan rasa.',
    menu: ['Foie Gras', 'Truffle Pasta', 'Sea Bass', 'Crème Brûlée'],
  },
  {
    id: 'r09', cat: 1, catName: 'Restoran & Kuliner',
    name: 'WebsiteKu Food Delivery',
    style: 'glassmorphism',
    primary: '#FF6B35', secondary: '#6C63FF', accent: '#00D4FF',
    description: 'Layanan pesan antar makanan dengan UI modern glassmorphism. Cepat dan mudah digunakan.',
    tags: ['delivery', 'pesan antar', 'online', 'cepat'],
    headline: 'Makanan Lezat, Sampai di Pintu',
    sub: 'Pesan sekarang, tiba dalam 30 menit. Lebih dari 100 menu pilihan.',
    menu: ['Nasi Goreng', 'Ayam Geprek', 'Pizza', 'Burger'],
  },
  {
    id: 'r10', cat: 1, catName: 'Restoran & Kuliner',
    name: 'WebsiteKu Healthy Food',
    style: 'futuristic',
    primary: '#00FF87', secondary: '#6C63FF', accent: '#00D4FF',
    description: 'Restoran makanan sehat dengan tampilan futuristik dan modern. Untuk brand health-conscious.',
    tags: ['healthy', 'sehat', 'vegan', 'organic'],
    headline: 'EAT CLEAN. LIVE BOLD.',
    sub: 'Program makan sehat berbasis data nutrisi untuk gaya hidup optimal Anda.',
    menu: ['Acai Bowl', 'Green Smoothie', 'Quinoa Salad', 'Detox Juice'],
  },

  /* ===========================
     KATEGORI 2 — PROPERTY & KONSTRUKSI
     =========================== */
  {
    id: 'p01', cat: 2, catName: 'Property & Konstruksi',
    name: 'WebsiteKu Property',
    style: 'corporate',
    primary: '#1A3C5E', secondary: '#4A90D9', accent: '#E8F4FD',
    description: 'Agency properti profesional dengan tampilan terpercaya dan bersih.',
    tags: ['properti', 'jual beli', 'investasi', 'agen'],
    headline: 'Temukan Properti Impian Anda',
    sub: 'Ribuan listing properti pilihan. Agen berpengalaman siap membantu.',
    menu: ['Rumah', 'Apartemen', 'Ruko', 'Tanah'],
  },
  {
    id: 'p02', cat: 2, catName: 'Property & Konstruksi',
    name: 'WebsiteKu Real Estate',
    style: 'luxury',
    primary: '#8B6914', secondary: '#C9A227', accent: '#1A1A2E',
    description: 'Real estate premium dengan tampilan mewah untuk properti eksklusif dan berkelas.',
    tags: ['real estate', 'mewah', 'premium', 'eksklusif'],
    headline: 'Luxury Living Redefined',
    sub: 'Properti eksklusif di lokasi strategis terbaik Indonesia.',
    menu: ['Villa', 'Penthouse', 'Cluster Elite', 'Waterfront'],
  },
  {
    id: 'p03', cat: 2, catName: 'Property & Konstruksi',
    name: 'WebsiteKu Villa',
    style: 'premium',
    primary: '#C9A227', secondary: '#0D1B2A', accent: '#FFFFFF',
    description: 'Website villa rental atau penjualan mewah. Untuk properti villa resort dan private.',
    tags: ['villa', 'resort', 'sewa', 'liburan'],
    headline: 'Your Private Paradise Awaits',
    sub: 'Villa mewah dengan pemandangan spektakuler dan fasilitas bintang lima.',
    menu: ['Villa Pantai', 'Villa Bukit', 'Villa Kolam', 'Villa Private'],
  },
  {
    id: 'p04', cat: 2, catName: 'Property & Konstruksi',
    name: 'WebsiteKu Developer',
    style: 'startup',
    primary: '#2563EB', secondary: '#7C3AED', accent: '#06B6D4',
    description: 'Developer properti modern dengan presentasi project yang impressive.',
    tags: ['developer', 'perumahan', 'cluster', 'modern'],
    headline: 'Bangun Masa Depan Bersama Kami',
    sub: 'Developer perumahan terpercaya dengan track record 15 tahun.',
    menu: ['Perumahan', 'Komersial', 'Mixed Use', 'Industrial'],
  },
  {
    id: 'p05', cat: 2, catName: 'Property & Konstruksi',
    name: 'WebsiteKu Interior',
    style: 'minimalist',
    primary: '#8B7355', secondary: '#E8DCC8', accent: '#2C2C2C',
    description: 'Studio desain interior dengan portofolio minimalis yang elegan.',
    tags: ['interior', 'desain', 'dekorasi', 'ruang'],
    headline: 'Ruang yang Mencerminkan Jiwa Anda',
    sub: 'Desain interior yang harmonis, fungsional, dan penuh estetika.',
    menu: ['Residential', 'Commercial', 'Hospitality', 'Office'],
  },
  {
    id: 'p06', cat: 2, catName: 'Property & Konstruksi',
    name: 'WebsiteKu Arsitek',
    style: 'dark',
    primary: '#6C63FF', secondary: '#00D4FF', accent: '#FFFFFF',
    description: 'Firma arsitektur dengan portfolio bold dan artistic. Monochrome dan impresif.',
    tags: ['arsitek', 'desain', 'bangunan', 'creative'],
    headline: 'Architecture That Speaks',
    sub: 'Merancang bangunan yang menginspirasi dan bertahan melewati waktu.',
    menu: ['Residential', 'Commercial', 'Public', 'Renovation'],
  },
  {
    id: 'p07', cat: 2, catName: 'Property & Konstruksi',
    name: 'WebsiteKu Kontraktor',
    style: 'futuristic',
    primary: '#F59E0B', secondary: '#1E3A5F', accent: '#00D4FF',
    description: 'Jasa kontraktor profesional dengan tampilan tegas dan terpercaya.',
    tags: ['kontraktor', 'pembangunan', 'renovasi', 'konstruksi'],
    headline: 'BUILDING THE FUTURE',
    sub: 'Kontraktor profesional bersertifikat untuk proyek skala residensial hingga komersial.',
    menu: ['Bangun Baru', 'Renovasi', 'Gedung', 'Infrastruktur'],
  },
  {
    id: 'p08', cat: 2, catName: 'Property & Konstruksi',
    name: 'WebsiteKu Perumahan',
    style: 'elegant',
    primary: '#4A7C59', secondary: '#F0E6D3', accent: '#2C5F2E',
    description: 'Pemasaran perumahan keluarga dengan nuansa hangat dan mengundang.',
    tags: ['perumahan', 'keluarga', 'cluster', 'hunian'],
    headline: 'Rumah Impian untuk Keluarga',
    sub: 'Hunian nyaman di lingkungan asri dengan fasilitas lengkap.',
    menu: ['Tipe 36', 'Tipe 45', 'Tipe 60', 'Tipe 72'],
  },
  {
    id: 'p09', cat: 2, catName: 'Property & Konstruksi',
    name: 'WebsiteKu Apartemen',
    style: 'glassmorphism',
    primary: '#6C63FF', secondary: '#FF6584', accent: '#00D4FF',
    description: 'Marketing apartemen urban modern dengan tampilan futuristic glassmorphism.',
    tags: ['apartemen', 'urban', 'kota', 'investasi'],
    headline: 'Urban Living Elevated',
    sub: 'Apartemen premium di jantung kota dengan view dan fasilitas tak tertandingi.',
    menu: ['Studio', '1 BR', '2 BR', 'Penthouse'],
  },
  {
    id: 'p10', cat: 2, catName: 'Property & Konstruksi',
    name: 'WebsiteKu Furniture',
    style: 'neon',
    primary: '#FF6B35', secondary: '#6C63FF', accent: '#00FF87',
    description: 'Showroom furniture modern dengan tampilan yang eye-catching dan bold.',
    tags: ['furniture', 'mebel', 'interior', 'modern'],
    headline: 'FURNI YOUR WORLD',
    sub: 'Furniture desainer dengan material premium untuk rumah impian Anda.',
    menu: ['Living Room', 'Bedroom', 'Kitchen', 'Office'],
  },

  /* ===========================
     KATEGORI 3 — KESEHATAN & KECANTIKAN
     =========================== */
  {
    id: 'k01', cat: 3, catName: 'Kesehatan & Kecantikan',
    name: 'WebsiteKu Klinik',
    style: 'corporate',
    primary: '#0077B6', secondary: '#00B4D8', accent: '#E0F7FA',
    description: 'Klinik kesehatan profesional dengan tampilan bersih, terpercaya, dan meyakinkan.',
    tags: ['klinik', 'kesehatan', 'dokter', 'medis'],
    headline: 'Kesehatan Anda, Prioritas Kami',
    sub: 'Pelayanan medis profesional dengan tenaga dokter berpengalaman dan fasilitas modern.',
    menu: ['Umum', 'Spesialis', 'Lab', 'Farmasi'],
  },
  {
    id: 'k02', cat: 3, catName: 'Kesehatan & Kecantikan',
    name: 'WebsiteKu Dental',
    style: 'minimalist',
    primary: '#0EA5E9', secondary: '#E0F2FE', accent: '#1E3A5F',
    description: 'Klinik gigi bersih dan profesional. Tampilan minimalis yang menumbuhkan kepercayaan.',
    tags: ['gigi', 'dental', 'klinik', 'dokter gigi'],
    headline: 'Senyum Sempurna Dimulai di Sini',
    sub: 'Perawatan gigi profesional dengan teknologi modern dan tim dokter terlatih.',
    menu: ['Scaling', 'Bleaching', 'Veneer', 'Behel'],
  },
  {
    id: 'k03', cat: 3, catName: 'Kesehatan & Kecantikan',
    name: 'WebsiteKu Skincare',
    style: 'elegant',
    primary: '#E8A598', secondary: '#FFF0EC', accent: '#5C3D2E',
    description: 'Brand skincare dengan tampilan cantik dan feminin. Rose gold dan soft pink.',
    tags: ['skincare', 'kecantikan', 'perawatan kulit', 'beauty'],
    headline: 'Your Skin Deserves the Best',
    sub: 'Rangkaian skincare premium dengan formula inovatif untuk kulit sehat bercahaya.',
    menu: ['Cleanser', 'Serum', 'Moisturizer', 'Sunscreen'],
  },
  {
    id: 'k04', cat: 3, catName: 'Kesehatan & Kecantikan',
    name: 'WebsiteKu Beauty Clinic',
    style: 'glassmorphism',
    primary: '#EC4899', secondary: '#8B5CF6', accent: '#06B6D4',
    description: 'Beauty clinic modern dengan tampilan glassmorphism yang elegan dan premium.',
    tags: ['kecantikan', 'perawatan', 'aesthetic', 'clinic'],
    headline: 'Percantik Diri, Percayai Kami',
    sub: 'Treatment kecantikan terkini dengan dokter spesialis dan teknologi terdepan.',
    menu: ['Filler', 'Botox', 'Laser', 'Facial'],
  },
  {
    id: 'k05', cat: 3, catName: 'Kesehatan & Kecantikan',
    name: 'WebsiteKu Spa',
    style: 'luxury',
    primary: '#7B6547', secondary: '#C9A87C', accent: '#F5F0E8',
    description: 'Spa mewah dengan nuansa relaksasi total. Earthy tones dan luxury feel.',
    tags: ['spa', 'relaksasi', 'wellness', 'mewah'],
    headline: 'Sanctuary of Serenity',
    sub: 'Manjakan tubuh dan pikiran di oasis ketenangan kami.',
    menu: ['Swedish Massage', 'Hot Stone', 'Aromatherapy', 'Body Scrub'],
  },
  {
    id: 'k06', cat: 3, catName: 'Kesehatan & Kecantikan',
    name: 'WebsiteKu Fitness',
    style: 'neon',
    primary: '#FF0090', secondary: '#00FF41', accent: '#FFD700',
    description: 'Studio fitness penuh energi dengan tampilan neon yang membakar semangat.',
    tags: ['fitness', 'olahraga', 'gym', 'workout'],
    headline: 'NO LIMITS. NO EXCUSES.',
    sub: 'Studio fitness premium dengan peralatan terlengkap dan trainer profesional.',
    menu: ['Cardio', 'Strength', 'HIIT', 'Yoga'],
  },
  {
    id: 'k07', cat: 3, catName: 'Kesehatan & Kecantikan',
    name: 'WebsiteKu Gym',
    style: 'dark',
    primary: '#EF4444', secondary: '#F97316', accent: '#FBBF24',
    description: 'Gym hardcore dengan tema gelap dan maskulin. Bold, powerful, dan motivating.',
    tags: ['gym', 'otot', 'training', 'powerlifting'],
    headline: 'FORGE YOUR LEGACY',
    sub: 'Gym dengan peralatan profesional dan komunitas atlet yang solid.',
    menu: ['Free Weights', 'Machine Zone', 'Cardio Deck', 'PT Session'],
  },
  {
    id: 'k08', cat: 3, catName: 'Kesehatan & Kecantikan',
    name: 'WebsiteKu Nutrition',
    style: 'startup',
    primary: '#10B981', secondary: '#059669', accent: '#D1FAE5',
    description: 'Brand nutrisi dan suplemen dengan tampilan segar, bersih, dan terpercaya.',
    tags: ['nutrisi', 'suplemen', 'sehat', 'protein'],
    headline: 'Fuel Your Potential',
    sub: 'Suplemen olahraga premium berbahan alami untuk performa optimal Anda.',
    menu: ['Protein', 'BCAA', 'Pre-Workout', 'Vitamins'],
  },
  {
    id: 'k09', cat: 3, catName: 'Kesehatan & Kecantikan',
    name: 'WebsiteKu Apotek',
    style: 'futuristic',
    primary: '#10B981', secondary: '#0D1B2A', accent: '#00D4FF',
    description: 'Apotek digital modern dengan tampilan futuristik dan sistem order online.',
    tags: ['apotek', 'obat', 'farmasi', 'online'],
    headline: 'PHARMACY 2.0',
    sub: 'Pesan obat dan vitamin secara online, pengiriman ke rumah dalam 1 jam.',
    menu: ['Obat Bebas', 'Resep Dokter', 'Vitamin', 'Alat Kesehatan'],
  },
  {
    id: 'k10', cat: 3, catName: 'Kesehatan & Kecantikan',
    name: 'WebsiteKu Healthcare',
    style: 'premium',
    primary: '#0EA5E9', secondary: '#0F172A', accent: '#38BDF8',
    description: 'Platform healthcare premium dengan tampilan profesional dan modern.',
    tags: ['healthcare', 'rumah sakit', 'platform', 'medis'],
    headline: 'Advanced Healthcare Solutions',
    sub: 'Platform kesehatan terintegrasi untuk konsultasi, booking, dan rekam medis.',
    menu: ['Konsultasi', 'Rawat Jalan', 'Rawat Inap', 'Medical Check'],
  },

  /* ===========================
     KATEGORI 4 — DIGITAL & TEKNOLOGI
     =========================== */
  {
    id: 'd01', cat: 4, catName: 'Digital & Teknologi',
    name: 'WebsiteKu Agency',
    style: 'startup',
    primary: '#6C63FF', secondary: '#FF6584', accent: '#00D4FF',
    description: 'Digital agency dengan tampilan kreatif, bold, dan memukau. Siap mengesankan klien.',
    tags: ['agency', 'digital', 'kreatif', 'branding'],
    headline: 'We Build Brands That Matter',
    sub: 'Agensi digital kreatif yang mengubah ide menjadi pengalaman yang tak terlupakan.',
    menu: ['Branding', 'Web Design', 'Social Media', 'SEO'],
  },
  {
    id: 'd02', cat: 4, catName: 'Digital & Teknologi',
    name: 'WebsiteKu Startup',
    style: 'neon',
    primary: '#00FF87', secondary: '#6C63FF', accent: '#FF6584',
    description: 'Landing page startup tech yang futuristik dengan neon glow dan dark theme.',
    tags: ['startup', 'tech', 'innovasi', 'growth'],
    headline: 'THE FUTURE IS NOW',
    sub: 'Platform inovatif yang memecahkan masalah nyata dengan teknologi terdepan.',
    menu: ['Product', 'Pricing', 'Team', 'Blog'],
  },
  {
    id: 'd03', cat: 4, catName: 'Digital & Teknologi',
    name: 'WebsiteKu SaaS',
    style: 'glassmorphism',
    primary: '#6C63FF', secondary: '#EC4899', accent: '#06B6D4',
    description: 'Landing page SaaS modern dengan glassmorphism dan UI yang clean.',
    tags: ['SaaS', 'software', 'subscription', 'cloud'],
    headline: 'Your Workflow, Supercharged',
    sub: 'Aplikasi SaaS yang memudahkan tim Anda bekerja lebih cepat dan efisien.',
    menu: ['Features', 'Pricing', 'Integration', 'Docs'],
  },
  {
    id: 'd04', cat: 4, catName: 'Digital & Teknologi',
    name: 'WebsiteKu Hosting',
    style: 'corporate',
    primary: '#1E40AF', secondary: '#3B82F6', accent: '#DBEAFE',
    description: 'Provider hosting profesional dengan tampilan terpercaya dan terstruktur.',
    tags: ['hosting', 'cloud', 'server', 'domain'],
    headline: 'Hosting Andalan Bisnis Indonesia',
    sub: '99.9% uptime, support 24/7, dan infrastruktur kelas dunia untuk website Anda.',
    menu: ['Shared Hosting', 'VPS', 'Dedicated', 'Domain'],
  },
  {
    id: 'd05', cat: 4, catName: 'Digital & Teknologi',
    name: 'WebsiteKu AI',
    style: 'futuristic',
    primary: '#00D4FF', secondary: '#6C63FF', accent: '#00FF87',
    description: 'Platform AI dan machine learning dengan tampilan high-tech dan futuristik.',
    tags: ['AI', 'machine learning', 'artificial intelligence', 'tech'],
    headline: 'INTELLIGENCE AMPLIFIED',
    sub: 'Solusi AI yang mengotomasi proses bisnis dan meningkatkan efisiensi hingga 10x.',
    menu: ['AI Tools', 'API', 'Enterprise', 'Research'],
  },
  {
    id: 'd06', cat: 4, catName: 'Digital & Teknologi',
    name: 'WebsiteKu Crypto',
    style: 'dark',
    primary: '#F7931A', secondary: '#00D4FF', accent: '#00FF87',
    description: 'Platform kripto dan blockchain dengan tampilan dark dan modern.',
    tags: ['crypto', 'blockchain', 'web3', 'DeFi'],
    headline: 'Trade Smarter, Not Harder',
    sub: 'Platform trading kripto terpercaya dengan analitik real-time dan keamanan tingkat tinggi.',
    menu: ['Trading', 'Portfolio', 'DeFi', 'NFT'],
  },
  {
    id: 'd07', cat: 4, catName: 'Digital & Teknologi',
    name: 'WebsiteKu Fintech',
    style: 'premium',
    primary: '#10B981', secondary: '#0F172A', accent: '#34D399',
    description: 'Fintech platform premium dengan tampilan profesional dan inspire kepercayaan.',
    tags: ['fintech', 'keuangan', 'payment', 'banking'],
    headline: 'Financial Freedom Starts Here',
    sub: 'Platform keuangan digital yang aman, cepat, dan mudah digunakan semua orang.',
    menu: ['Transfer', 'Investasi', 'Pinjaman', 'Asuransi'],
  },
  {
    id: 'd08', cat: 4, catName: 'Digital & Teknologi',
    name: 'WebsiteKu Software House',
    style: 'minimalist',
    primary: '#334155', secondary: '#94A3B8', accent: '#0EA5E9',
    description: 'Software house profesional dengan portfolio minimalis dan clean.',
    tags: ['software', 'development', 'programming', 'IT'],
    headline: 'Code That Transforms Business',
    sub: 'Tim developer berpengalaman siap membangun solusi software sesuai kebutuhan Anda.',
    menu: ['Web Dev', 'Mobile App', 'API', 'Maintenance'],
  },
  {
    id: 'd09', cat: 4, catName: 'Digital & Teknologi',
    name: 'WebsiteKu Cyber Security',
    style: 'neon',
    primary: '#00FF41', secondary: '#FF0000', accent: '#00D4FF',
    description: 'Perusahaan keamanan siber dengan tampilan hacker-tech yang intens.',
    tags: ['security', 'cyber', 'hacking', 'protection'],
    headline: 'DEFEND. DETECT. RESPOND.',
    sub: 'Solusi keamanan siber komprehensif untuk melindungi aset digital bisnis Anda.',
    menu: ['Pen Test', 'SOC', 'Threat Intel', 'Training'],
  },
  {
    id: 'd10', cat: 4, catName: 'Digital & Teknologi',
    name: 'WebsiteKu Digital Marketing',
    style: 'elegant',
    primary: '#8B5CF6', secondary: '#F8EEFF', accent: '#5B21B6',
    description: 'Agensi digital marketing dengan tampilan kreatif dan profesional.',
    tags: ['digital marketing', 'SEO', 'ads', 'konten'],
    headline: 'Grow Your Business Digitally',
    sub: 'Strategi digital marketing yang terukur dan hasil yang nyata untuk bisnis Anda.',
    menu: ['SEO', 'Google Ads', 'Social Media', 'Content'],
  },

  /* ===========================
     KATEGORI 5 — UMKM & BISNIS UMUM
     =========================== */
  {
    id: 'u01', cat: 5, catName: 'UMKM & Bisnis Umum',
    name: 'WebsiteKu Laundry',
    style: 'minimalist',
    primary: '#0EA5E9', secondary: '#E0F2FE', accent: '#0369A1',
    description: 'Jasa laundry bersih dan segar dengan tampilan minimalis dan rapi.',
    tags: ['laundry', 'cuci', 'bersih', 'setrika'],
    headline: 'Pakaian Bersih, Hidup Nyaman',
    sub: 'Layanan laundry profesional dengan pickup & delivery gratis area sekitar.',
    menu: ['Cuci Kiloan', 'Dry Clean', 'Express', 'Bed Cover'],
  },
  {
    id: 'u02', cat: 5, catName: 'UMKM & Bisnis Umum',
    name: 'WebsiteKu Bengkel',
    style: 'dark',
    primary: '#DC2626', secondary: '#92400E', accent: '#FCD34D',
    description: 'Bengkel otomotif tegas dengan tampilan dark dan maskulin.',
    tags: ['bengkel', 'otomotif', 'servis', 'mobil'],
    headline: 'Servis Terpercaya untuk Kendaraan Anda',
    sub: 'Bengkel profesional dengan mekanik berpengalaman dan spare part original.',
    menu: ['Servis Rutin', 'Tune Up', 'Body Repair', 'AC Mobil'],
  },
  {
    id: 'u03', cat: 5, catName: 'UMKM & Bisnis Umum',
    name: 'WebsiteKu Travel',
    style: 'startup',
    primary: '#0EA5E9', secondary: '#8B5CF6', accent: '#F59E0B',
    description: 'Agen perjalanan wisata dengan tampilan cerah dan mengundang petualangan.',
    tags: ['travel', 'wisata', 'tour', 'holiday'],
    headline: 'Jelajahi Dunia Bersama Kami',
    sub: 'Paket wisata terjangkau ke seluruh penjuru Indonesia dan mancanegara.',
    menu: ['Domestik', 'Internasional', 'Honeymoon', 'Umroh'],
  },
  {
    id: 'u04', cat: 5, catName: 'UMKM & Bisnis Umum',
    name: 'WebsiteKu Toko Online',
    style: 'glassmorphism',
    primary: '#EC4899', secondary: '#8B5CF6', accent: '#06B6D4',
    description: 'Toko online modern dengan UI glassmorphism yang menarik dan mudah digunakan.',
    tags: ['toko online', 'ecommerce', 'jualan', 'belanja'],
    headline: 'Belanja Mudah, Harga Terjangkau',
    sub: 'Ribuan produk pilihan berkualitas dengan pengiriman ke seluruh Indonesia.',
    menu: ['Elektronik', 'Fashion', 'Rumah', 'Kecantikan'],
  },
  {
    id: 'u05', cat: 5, catName: 'UMKM & Bisnis Umum',
    name: 'WebsiteKu Fashion',
    style: 'elegant',
    primary: '#BE185D', secondary: '#FDF2F8', accent: '#831843',
    description: 'Brand fashion wanita dengan tampilan elegan, feminin, dan berkelas.',
    tags: ['fashion', 'pakaian', 'wanita', 'busana'],
    headline: 'Dress to Express Yourself',
    sub: 'Koleksi fashion wanita eksklusif yang memadukan gaya modern dan kenyamanan.',
    menu: ['New Arrival', 'Best Seller', 'Sale', 'Hijab'],
  },
  {
    id: 'u06', cat: 5, catName: 'UMKM & Bisnis Umum',
    name: 'WebsiteKu Pet Shop',
    style: 'neon',
    primary: '#FF6B35', secondary: '#00FF87', accent: '#FFD700',
    description: 'Pet shop dengan tampilan fun, berwarna-warni, dan penuh energi.',
    tags: ['pet shop', 'hewan', 'anjing', 'kucing'],
    headline: 'HAPPY PETS, HAPPY LIFE!',
    sub: 'Semua kebutuhan hewan peliharaan Anda tersedia di satu tempat.',
    menu: ['Makanan', 'Grooming', 'Aksesoris', 'Klinik Hewan'],
  },
  {
    id: 'u07', cat: 5, catName: 'UMKM & Bisnis Umum',
    name: 'WebsiteKu Event Organizer',
    style: 'luxury',
    primary: '#9B111E', secondary: '#C9A227', accent: '#1A1A2E',
    description: 'Event organizer premium dengan tampilan mewah dan berkelas tinggi.',
    tags: ['event', 'organizer', 'pesta', 'seminar'],
    headline: 'Moments That Last Forever',
    sub: 'EO profesional yang mengubah impian Anda menjadi acara yang sempurna.',
    menu: ['Wedding', 'Corporate', 'Birthday', 'Concert'],
  },
  {
    id: 'u08', cat: 5, catName: 'UMKM & Bisnis Umum',
    name: 'WebsiteKu Wedding',
    style: 'premium',
    primary: '#C9A227', secondary: '#1A0A2E', accent: '#F8E8FF',
    description: 'Wedding organizer mewah dengan tampilan romantis dan anggun.',
    tags: ['wedding', 'pernikahan', 'dekorasi', 'catering'],
    headline: 'Your Dream Wedding Begins Here',
    sub: 'Layanan pernikahan lengkap dan profesional untuk hari istimewa yang tak terlupakan.',
    menu: ['Dekorasi', 'Catering', 'Foto & Video', 'Paket Lengkap'],
  },
  {
    id: 'u09', cat: 5, catName: 'UMKM & Bisnis Umum',
    name: 'WebsiteKu Kursus',
    style: 'corporate',
    primary: '#7C3AED', secondary: '#DDD6FE', accent: '#4C1D95',
    description: 'Lembaga kursus dan pendidikan dengan tampilan profesional dan terpercaya.',
    tags: ['kursus', 'pendidikan', 'les', 'belajar'],
    headline: 'Investasikan Masa Depan Anda',
    sub: 'Kursus online dan offline dengan instruktur berpengalaman di bidangnya.',
    menu: ['Bahasa', 'Komputer', 'Bisnis', 'Skill Digital'],
  },
  {
    id: 'u10', cat: 5, catName: 'UMKM & Bisnis Umum',
    name: 'WebsiteKu Konsultan',
    style: 'futuristic',
    primary: '#6C63FF', secondary: '#0D1B2A', accent: '#00D4FF',
    description: 'Firma konsultan bisnis dengan tampilan premium dan futuristik.',
    tags: ['konsultan', 'bisnis', 'strategi', 'manajemen'],
    headline: 'STRATEGY. EXECUTION. RESULTS.',
    sub: 'Konsultan bisnis berpengalaman untuk membawa perusahaan Anda ke level berikutnya.',
    menu: ['Strategi', 'Operasional', 'SDM', 'Keuangan'],
  },
];
